version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
      
  db-it:
    image: postgres
    restart: always
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: it
      
   